export const TESTGET_SUCCESS = 'TESTGET_SUCCESS'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const GETALLUSER_SUCCESS = 'GETALLUSER_SUCCESS'

export const GETALLVIDEO_SUCCESS = 'GETALLVIDEO_SUCCESS'
export const GETDETAILVIDEO_SUCCESS = 'GETDETAILVIDEO_SUCCESS'
export const GETALLCOLLECTVIDEO_SUCCESS = 'GETALLCOLLECTVIDEO_SUCCESS'

